apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-postgres-pvc
  namespace: inventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-postgres
  template:
    metadata:
      labels:
        app: inventory-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - inventory_user
                - -d
                - inventory_db
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - inventory_user
                - -d
                - inventory_db
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: inventory-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres
  namespace: inventory
spec:
  selector:
    app: inventory-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
